#production Profile
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://${datasource.url}:3306/ott_tving?useUnicode=true&characterEncoding=UTF-8
    username: ${datasource.username}
    password: ${datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none

logging:
  level:
    org.hibernate.sql: warn