#default Profile
server:
  port: 8080

jwt:
  secret: src/main/resources/files/secretkey.txt
  token:
    access-expiration-time: 300000  # 12시간
    refresh-expiration-time: 300000  # 7일

spring:
  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    open-in-view: false
