#develop Profile
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: ${datasource.url} #jdbc:mysql://52.78.80.12:3306/ott_tving_dev?useUnicode=true&characterEncoding=UTF-8
    username: ${datasource.username} #manager01
    password: ${datasource.password} #1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: true
        show_sql: true

logging:
  level:
    org.hibernate.sql: debug

